development:
  adapter: postgresql
  encoding: unicode
  database: project3_dev
  pool: 5
  username: kingsley
  password: weetabix

test:
  adapter: postgresql
  encoding: unicode
  database: project3_test
  pool: 5
  username: kingsley
  password: weetabix

production:
  adapter: postgresql
  encoding: unicode
  database: project3
  pool: 5
  username: kingsley
  password: weetabix